### ISSUE TITLE
Problem with systemctl and pgwatch2 gathering daemon

### ISSUE THREAD

**Issue by viewpnt** [cybertec-postgresql/pgwatch2#172]
Hi: 
I installed pgwatch2 without docker, and if I run the pgwatch2 gathering daemon from the command line, everything is working fine... 

```
/home/pgwatch2/pgwatch2 --host=127.0.0.1 --user=pgwatch2 --password=pgwatch2  --ihost=127.0.0.1 --iuser=pgwatch2 --ipassword=pgwatch2
```
...but when I try to use [pgwatch2.service](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/startup-scripts/pgwatch2.service) a series of errors start to appear almost immediately in /var/log/messages, I tried to run the service as User=root, but the same problem...
¿any idea what is causing this?

```
#systemctl cat pgwatch2
#/etc/systemd/system/pgwatch2.service
[Unit]
Description=Pgwatch2 Gathering Daemon

[Service]
User=pgwatch2
Type=notify
ExecStart=/home/pgwatch2/pgwatch2 --host=127.0.0.1 --user=pgwatch2 --password=pgwatch2  --ihost=127.0.0.1 --iuser=pgwatch2 --ipassword=pgwatch2
WatchdogSec=60s
Restart=on-failure

[Install]
WantedBy=multi-user.target

```
One thing I notice, the ERRO MetricGathererLoop does not appear when pgwatch2 is run from the command line and now appears several times before the "watchdog timeout".
systemctl restarts the service automatically, but before a minute, it fails again and again.

```
#tail -f /var/log//messages
pgwatch2[4000]: 2019/08/13 21:13:14 ERRO MetricGathererLoop: Failed to fetch metric data for [db2_pgbench16:kpi]: pq: recovery is in progress
Aug 13 21:13:15  pgwatch2[4000]: 2019/08/13 21:13:15 ERRO MetricGathererLoop: Failed to fetch metric data for [db2_pgbench17:kpi]: pq: recovery is in progress
systemd: pgwatch2.service watchdog timeout (limit 1min)!                                                  
pgwatch2: SIGABRT: abort                                                                                  
pgwatch2: PC=0x45bda1 m=0 sigcode=0                                                                       
pgwatch2: goroutine 21 [syscall]:                                                                         
pgwatch2: runtime.notetsleepg(0xf80900, 0xffffffffffffffff, 0xc00003e7b8)                                 
pgwatch2: /usr/lib/golang/src/runtime/lock_futex.go:227 +0x37 fp=0xc00003e788 sp=0xc00003e758 pc=0x40c5d7 
pgwatch2: os/signal.signal_recv(0xab3078)                                                                 
pgwatch2: /usr/lib/golang/src/runtime/sigqueue.go:139 +0x9c fp=0xc00003e7b0 sp=0xc00003e788 pc=0x442dac   
pgwatch2: os/signal.loop()                                                                                
pgwatch2: /usr/lib/golang/src/os/signal/signal_unix.go:23 +0x22 fp=0xc00003e7e0 sp=0xc00003e7b0 pc=0x84294
pgwatch2: runtime.goexit()                                                                                
pgwatch2: /usr/lib/golang/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc00003e7e8 sp=0xc00003e7e0 pc=0x459f51   
pgwatch2: created by os/signal.init.0                                                                     
pgwatch2: /usr/lib/golang/src/os/signal/signal_unix.go:29 +0x41                                           
pgwatch2: goroutine 1 [sleep]:                                                                            
pgwatch2: time.Sleep(0x1bf08eb000)                                                                        
pgwatch2: /usr/lib/golang/src/runtime/time.go:105 +0x14f                                                  
pgwatch2: main.main()                                                                                     
pgwatch2: /root/pgwatch2/pgwatch2/pgwatch2.go:3665 +0x14d2                                                
pgwatch2: goroutine 22 [select]:                                                                          
pgwatch2: database/sql.(*DB).connectionOpener(0xc000116240, 0xb3b700, 0xc000094d80)                       
pgwatch2: /usr/lib/golang/src/database/sql/sql.go:1001 +0xe8                                              
pgwatch2: created by database/sql.OpenDB                                                                  
```
```
# /home/pgwatch2/pgwatch2 --version
d8edca5ef263a691c7ceaa70da37c52d02b78b3c (2019-08-12 19:43:40 +0300)

# go version
go version go1.11.5 linux/amd64

# cat /etc/redhat-release 
CentOS Linux release 7.6.1810 (Core)

# getenforce 
Permissive

# ldd /home/pgwatch2/pgwatch2 
	linux-vdso.so.1 =>  (0x00007ffccff27000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fa060539000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fa06016c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa060755000)
```
Thank you for your help.

EDIT:
After [further investigation](https://www.freedesktop.org/software/systemd/man/systemd.service.html#WatchdogSec=) of the error "systemd: pgwatch2.service watchdog timeout (limit 1min)!",  I removed WatchdogSec=60s from pgwatch2.service, and now the the gathering daemon does not show  the errors and it no longer get restarted by systemd. Could it be possible that the pgwarch2 daemon does not call sd_notify(3) ? 

Now another kind of errors started to appear... too many connections for role "pgwatch2" , and there is no collection of metrics. I configured a connection limit of 20 for the pgwatch2 role. 

Any ideas how to solve this error? 
```
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench4:psutil_disk_io_total]: pq: too many connections for role "pgwatch2"  
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench7:replication]: pq: too many connections for role "pgwatch2"           
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench15:locks]: pq: too many connections for role "pgwatch2"                
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench9:psutil_disk]: pq: too many connections for role "pgwatch2"           
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench8:stat_ssl]: pq: too many connections for role "pgwatch2"              
ERRO MetricGathererLoop: Failed to fetch metric data for [db3_pgbench10:psutil_cpu]: pq: too many connections for role "pgwatch2"           
ERRO MetricGathererLoop: Failed to fetch metric data for [db3_pgbench3:psutil_mem]: pq: too many connections for role "pgwatch2"            
ERRO MetricGathererLoop: Failed to fetch metric data for [db3_pgbench7:backends]: pq: too many connections for role "pgwatch2"              
ERRO MetricGathererLoop: Failed to fetch metric data for [db3_pgbench7:stat_ssl]: pq: too many connections for role "pgwatch2"              
ERRO MetricGathererLoop: Failed to fetch metric data for [db3_pgbench8:stat_ssl]: pq: too many connections for role "pgwatch2"              
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench2:locks_mode]: pq: too many connections for role "pgwatch2"            
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench12:stat_statements_calls]: pq: too many connections for role "pgwatch2"
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench8:db_stats]: pq: too many connections for role "pgwatch2"              
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench3:backends]: pq: too many connections for role "pgwatch2"              
ERRO MetricGathererLoop: Failed to fetch metric data for [db1_pgbench7:wal]: pq: too many connections for role "pgwatch2"   

```

EDIT2:
Funny thing... after restarting the database, and restarting the pgwatch2 service, without the WatchdogSec=60s parameter, now everything is working fine. It appears that every time the service crashed, it left open connections in idle state, causing the "too many connections" error.

The question still remains... does pgwatch2 does not support WatchdogSec ? or is there a bug?

**Comment by kmoppel** [comment]
You're right @viewpnt , currenttly the collector only sends once the "ready" signal ([here](https://github.com/cybertec-postgresql/pgwatch2/blob/master/pgwatch2/pgwatch2.go#L3387)).
Not sure about the need for notify(3) as the main loop is quite foolproof...but adding `Restart=on-failure` is a good idea for sure. Will add that..

**Comment by kmoppel** [comment]
And about 'too many connections' - I think it's "normal behaviour" as you seem to have quite some similarly named DB-s on same test clusters probably and there's no syncing of fetching between independent DB-s.
