### ISSUE TITLE
Web.py: ERROR: Could not connect to Postgres 

### ISSUE THREAD

**Issue by rostamiani** [cybertec-postgresql/pgwatch2#316]
I installed the Web UI but when execution there is errors. It seems that connection to pgwatch2_metrics is succesfull but it cannot connect to the config database.

![image](https://user-images.githubusercontent.com/1157108/98080167-41037d80-1e8a-11eb-921f-0617630abfa5.png)

I'm executing with this command:

```shell
python3 web.py --datastore=postgres --pg-metric-store-conn-str="dbname=pgwatch2_metrics user=pgwatch2"
```

And these are the errors:

```log
2020-11-04 10:38:20,129 ERROR 403482 failed to execute "select 1 as x" on datastore
Traceback (most recent call last):
  File "/etc/pgwatch2/webpy/datadb.py", line 37, in execute
    conn = getConnection(connection_string_metrics) if on_metric_store else getConnection(conn_str)
  File "/etc/pgwatch2/webpy/datadb.py", line 27, in getConnection
    conn = psycopg2.connect(conn_str if conn_str else connection_string)    # default to configDB
  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATAL:  password authentication failed for user "pgwatch2"
FATAL:  password authentication failed for user "pgwatch2"

[04/Nov/2020:10:38:20] ENGINE Listening for SIGTERM.
2020-11-04 10:38:20,140 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Listening for SIGTERM.
[04/Nov/2020:10:38:20] ENGINE Listening for SIGHUP.
2020-11-04 10:38:20,140 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Listening for SIGHUP.
[04/Nov/2020:10:38:20] ENGINE Listening for SIGUSR1.
2020-11-04 10:38:20,140 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Listening for SIGUSR1.
[04/Nov/2020:10:38:20] ENGINE Bus STARTING
2020-11-04 10:38:20,140 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Bus STARTING
[04/Nov/2020:10:38:20] ENGINE Started monitor thread 'Autoreloader'.
2020-11-04 10:38:20,141 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Started monitor thread 'Autoreloader'.
[04/Nov/2020:10:38:20] ENGINE Serving on http://0.0.0.0:8081
2020-11-04 10:38:20,243 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Serving on http://0.0.0.0:8081
[04/Nov/2020:10:38:20] ENGINE Bus STARTED
2020-11-04 10:38:20,244 INFO 403482 [04/Nov/2020:10:38:20] ENGINE Bus STARTED
2.180.22.222 - - [04/Nov/2020:10:38:26] "GET /dbs HTTP/1.1" 200 22870 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
2020-11-04 10:38:26,873 INFO 403482 2.180.22.222 - - [04/Nov/2020:10:38:26] "GET /dbs HTTP/1.1" 200 22870 "" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:81.0) Gecko/20100101 Firefox/81.0"
```

**Comment by kmoppel** [comment]
Hi, seems like a plain password problem: `password authentication failed for user "pgwatch2"`. For example add an "password=xyz" to --pg-metric-store-conn-str or use `.pgpass`.
I assume this was a custom install, not the pre-configured Docker image. Re-open is so still.
