### ISSUE TITLE
Usage problem

### ISSUE THREAD

**Issue by GMOSMAR** [cybertec-postgresql/pgwatch2#388]
Hi
I downloaded the precompiled RPM for the pgwatch2-ddaemon, but I'm not able to start it.
Are there some requirements?

/home/postgres [PGQ01]$ /usr/bin/pgwatch2-daemon --version
`b39dfdfeb1c8193867abb0c50fe1999c18903af3` (2021-05-04T08:34:55Z)
/home/postgres [PGQ01]$ /usr/bin/pgwatch2-daemon --ping
panic: setting PGLOCALEDIR not supported

goroutine 1 [running]:
github.com/lib/pq.parseEnviron.func2(...)
        /home/krl/go/pkg/mod/github.com/lib/pq@v1.8.0/conn.go:1921
github.com/lib/pq.parseEnviron(0xc000030600, 0x5f, 0x5f, 0xc000093380)
        /home/krl/go/pkg/mod/github.com/lib/pq@v1.8.0/conn.go:1974 +0xf57
github.com/lib/pq.NewConnector(0xc00003e090, 0x86, 0xc0000bc188, 0xc0000802a0, 0xc0000802a0)
        /home/krl/go/pkg/mod/github.com/lib/pq@v1.8.0/connector.go:56 +0x145
github.com/lib/pq.DialOpen(0xcc1aa0, 0xc0000802a0, 0xc00003e090, 0x86, 0x203000, 0x203000, 0x203000, 0xc8)
        /home/krl/go/pkg/mod/github.com/lib/pq@v1.8.0/conn.go:280 +0x39
github.com/lib/pq.Open(...)
        /home/krl/go/pkg/mod/github.com/lib/pq@v1.8.0/conn.go:275
github.com/lib/pq.(*Driver).Open(0x10c1c60, 0xc00003e090, 0x86, 0x0, 0x0, 0x7f1e40e87100, 0xc000090000)
        /home/krl/go/pkg/mod/github.com/lib/pq@v1.8.0/conn.go:48 +0x9f
database/sql.dsnConnector.Connect(...)
        /usr/local/go/src/database/sql/sql.go:707
database/sql.(*DB).conn(0xc00008edd0, 0xcc7be0, 0xc000126010, 0xc000053301, 0xae4680, 0xc0000533b0, 0xae4680)
        /usr/local/go/src/database/sql/sql.go:1294 +0x204
database/sql.(*DB).PingContext(0xc00008edd0, 0xcc7be0, 0xc000126010, 0x9, 0xb167bb)
        /usr/local/go/src/database/sql/sql.go:799 +0x90
database/sql.(*DB).Ping(...)
        /usr/local/go/src/database/sql/sql.go:817
main.InitAndTestConfigStoreConnection(0xb15be1, 0x9, 0xb167bb, 0x4, 0xb286df, 0x8, 0xb1b9f5, 0x8, 0x0, 0x0, ...)
        /home/krl/pgwatch2_github/pgwatch2/pgwatch2.go:407 +0x248
main.main()
        /home/krl/pgwatch2_github/pgwatch2/pgwatch2.go:4875 +0x8d91
/home/postgres [PGQ01]$

Regards
  Franco

**Comment by GMOSMAR** [comment]
Uuups, seemed to be a config problem. Sorry.
Now it is working.
