### ISSUE TITLE
RHEL8.3 Error on install pip3 install cryptography

### ISSUE THREAD

**Issue by shab2** [cybertec-postgresql/pgwatch2#513]
cd /etc/pgwatch2/webpy/
[pgwatch2@db-mon-wtc webpy]$ pip3 install -U -r requirements_pg_metrics.txt --proxy $http_proxy
Collecting cherrypy (from -r requirements_pg_metrics.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/f2/90/0cefa94206e064075f5648a1e39754e3f54f8babdc2ad9eec956adb8a80e/CherryPy-18.8.0-py2.py3-none-any.whl (348kB)
    100% |████████████████████████████████| 358kB 1.4MB/s
Collecting jinja2 (from -r requirements_pg_metrics.txt (line 2))
  Downloading https://files.pythonhosted.org/packages/20/9a/e5d9ec41927401e41aea8af6d16e78b5e612bca4699d417f646a9610a076/Jinja2-3.0.3-py3-none-any.whl (133kB)
    100% |████████████████████████████████| 143kB 1.9MB/s
Collecting psycopg2-binary (from -r requirements_pg_metrics.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/d7/1c/8d042630c5ff3c3e6d93c992bd7ecf516d577803b96781c6caa649bbf6e5/psycopg2-binary-2.9.3.tar.gz (380kB)
    100% |████████████████████████████████| 389kB 1.5MB/s
Collecting decorator (from -r requirements_pg_metrics.txt (line 4))
  Downloading https://files.pythonhosted.org/packages/d5/50/83c593b07763e1161326b3b8c6686f0f4b0f24d5526546bee538c89837d6/decorator-5.1.1-py3-none-any.whl
Collecting cryptography (from -r requirements_pg_metrics.txt (line 5))
  Downloading https://files.pythonhosted.org/packages/6d/0c/5e67831007ba6cd7e52c4095f053cf45c357739b0a7c46a45ddd50049019/cryptography-38.0.1.tar.gz (599kB)
    100% |████████████████████████████████| 604kB 1.9MB/s
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-8yvr8c92/cryptography/setup.py", line 17, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-8yvr8c92/cryptography/

[pgwatch2@db-mon-wtc webpy]$ pip3 --version
pip 9.0.3 from /usr/lib/python3.6/site-packages (python 3.6)

**Comment by shab2** [comment]
fiexd
