### ISSUE TITLE
Not able to setup custom session

### ISSUE THREAD

**Issue by michaelolson01** [cybertec-postgresql/pgwatch2#699]
followed these instructions :
https://pgwatch2.readthedocs.io/en/latest/custom_installation.html

`python3 web.py --datastore=postgres --pg-metric-store-conn-str="dbname=pgwatch2_metrics user=pgwatch2"
`
does not work.
```
2023-10-12 13:37:03,152 ERROR 479379 Changing DBs failed
Traceback (most recent call last):
  File "/home/michael/Repositories/pgwatch2/webpy/web.py", line 138, in dbs
    affected = pgwatch2.enable_all_dbs()
  File "/home/michael/Repositories/pgwatch2/webpy/pgwatch2.py", line 561, in enable_all_dbs
    ret, _ = datadb.execute(sql)
  File "/home/michael/Repositories/pgwatch2/webpy/datadb.py", line 45, in execute
    conn = getConnection(connection_string_metrics) if on_metric_store else getConnection(conn_str)
  File "/home/michael/Repositories/pgwatch2/webpy/datadb.py", line 35, in getConnection
    conn = psycopg2.connect(conn_str if conn_str else connection_string)    # default to configDB
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied
```
added password=xyz to connection string so it now looks like 
`python3 web.py --datastore=postgres --pg-metric-store-conn-str="dbname=pgwatch2_metrics user=pgwatch2 password=xyz"
`
and multiple version of the 'xyz' password given when setting up the user.
```
~/R/p/webpy (master)> python3 web.py --datastore=postgres --pg-metric-store-conn-str="dbname=pgwatch2_metrics user=pgwatch2 password=''"
Could not import InfluxDBClient - expected if using Postgres metric storage
2023-10-12 13:35:00,653 ERROR 479379 failed to execute "select 1 as x" on datastore
Traceback (most recent call last):
  File "/home/michael/Repositories/pgwatch2/webpy/datadb.py", line 45, in execute
    conn = getConnection(connection_string_metrics) if on_metric_store else getConnection(conn_str)
  File "/home/michael/Repositories/pgwatch2/webpy/datadb.py", line 35, in getConnection
    conn = psycopg2.connect(conn_str if conn_str else connection_string)    # default to configDB
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: fe_sendauth: no password supplied


2023-10-12 13:35:00,654 ERROR 479379 failed to execute "select 1 as x" on datastore
Traceback (most recent call last):
  File "/home/michael/Repositories/pgwatch2/webpy/datadb.py", line 45, in execute
    conn = getConnection(connection_string_metrics) if on_metric_store else getConnection(conn_str)
  File "/home/michael/Repositories/pgwatch2/webpy/datadb.py", line 35, in getConnection
    conn = psycopg2.connect(conn_str if conn_str else connection_string)    # default to configDB
  File "/usr/local/lib/python3.10/dist-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: FATAL:  Peer authentication failed for user "pgwatch2"
```

**Comment by krisavi** [comment]
Web UI is trying to connect to configuration DB and metric store DB. 

Currently you have issues connecting to config DB. It is not as well documented, but there are various flags to adjust parameters of Web UI connection.

In code the portion that has listed all properties is listed here:
https://github.com/cybertec-postgresql/pgwatch2/blob/master/webpy/web.py#L323-L374
