### ISSUE TITLE
Error 500 on pgwatch2 : "pgwatch2.monitored_db" does not exist

### ISSUE THREAD

**Issue by pmpetit** [cybertec-postgresql/pgwatch2#88]
Hello,
here is my conf : 
pgwatch2 dockerised, 

influxdb, grafana and pgsql db for conf are outside.

When i go to pgwatch2 homepage i get this error 500,
and in the db's log : 
```log
2018-07-12 07:12:08 GMT [6131] 10.150.29.88(35560) repmgr@[unknown] rtdkz1pgs11 : [1-1]ERROR:  replication slot "repmgr_slot_2" does not exist
2018-07-12 07:12:13 GMT [6163] 10.224.21.125(38990) ggate@pgwatch2 [unknown] : [1-1]ERROR:  relation "pgwatch2.monitored_db" does not exist at character 155
2018-07-12 07:12:13 GMT [6163] 10.224.21.125(38990) ggate@pgwatch2 [unknown] : [2-1]STATEMENT:  
	        select
	          *,
	          date_trunc('second', md_last_modified_on) as md_last_modified_on,
	          md_config::text
	        from
	          pgwatch2.monitored_db
	        order by
	          md_is_enabled desc, md_id
	    
```
```log
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 627, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cprequest.py", line 686, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/pgwatch2/webpy/web.py", line 227, in index
    for x in pgwatch2.get_all_monitored_dbs()]
  File "/pgwatch2/webpy/pgwatch2.py", line 43, in get_all_monitored_dbs
    return datadb.execute(sql)[0]
  File "/pgwatch2/webpy/datadb.py", line 36, in execute
    cur.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/psycopg2/extras.py", line 249, in execute
    return super(RealDictCursor, self).execute(query, vars)
psycopg2.ProgrammingError: relation "pgwatch2.monitored_db" does not exist
LINE 7:           pgwatch2.monitored_db
```

**Comment by pmpetit** [comment]
it was my fault sorry
